In [65]:
from google.colab import drive
drive.mount('/content/Mydrive')
%cd "/content/Mydrive/MyDrive/IOT_hackathon/Github/IOT_hackathon"

Drive already mounted at /content/Mydrive; to attempt to forcibly remount, call drive.mount("/content/Mydrive", force_remount=True).
/content/Mydrive/MyDrive/IOT_hackathon/Github/IOT_hackathon

In [66]:
%cd "/content/Mydrive/MyDrive/IOT_hackathon/Github/IOT_hackathon/data/S-DoT 유동인구 2021"

/content/Mydrive/MyDrive/IOT_hackathon/Github/IOT_hackathon/data/S-DoT 유동인구 2021

In [67]:
import pandas as pd
import numpy as np
import os
import requests
from tqdm import tqdm

In [68]:
data_ls = os.listdir()
data_ls = sorted(data_ls)[1:]

In [111]:
from pandas.io.parsers.python_parser import ParserError
df_whole = pd.DataFrame(columns = ['사이트명','방문자수','등록일자'])

for i in tqdm(range(len(data_ls))):
    try:
        df = pd.read_csv(data_ls[i], encoding='cp949',usecols=['사이트명','방문자수','등록일자'],low_memory=False)
    except ValueError:
        df = pd.read_csv(data_ls[i], encoding='cp949',usecols=['사이트명','방문자수 (명)','등록 일시'],low_memory=False)
        df.columns = ['사이트명','방문자수','등록일자']
    except ParserError:
        pass
    
    except TypeError:
        pass
    df.등록일자 = pd.to_datetime(df.등록일자, errors='coerce')
    df = df.groupby([pd.Grouper(freq='H', key='등록일자'), '사이트명']).mean().reset_index()
    df = df.astype({'사이트명':'int', '방문자수':'int'})
    df_whole = pd.concat([df_whole, df])

df_whole.sort_values(by=['사이트명','등록일자'])
df_whole.reset_index()
df_whole.to_csv('SDOT_population.csv')

100%|██████████| 54/54 [00:12<00:00,  4.45it/s]

In [112]:
df_whole.sort_values(by=['등록일자'])

       사이트명 방문자수                등록일자
0      2992  197 2020-12-28 00:00:00
27     3019  143 2020-12-28 00:00:00
28     3020  204 2020-12-28 00:00:00
29     3021   99 2020-12-28 00:00:00
30     3022  133 2020-12-28 00:00:00
...     ...  ...                 ...
15268  3019  168 2022-01-02 23:00:00
15267  3018  129 2022-01-02 23:00:00
15266  3017  187 2022-01-02 23:00:00
15263  3014  159 2022-01-02 23:00:00
15337  4050    0 2022-01-02 23:00:00

[789720 rows x 3 columns]

In [102]:
df = pd.read_csv(data_ls[18],encoding='cp949', low_memory = False)

In [105]:
data_ls[18]

'S-DoT_WALK_2021.05.10-05.16.csv'

In [106]:
pd.to_datetime(df['등록일자'],errors='coerce')

0        2021-05-10 00:00:00
1        2021-05-10 00:00:00
2        2021-05-10 00:00:00
3        2021-05-10 00:00:00
4        2021-05-10 00:00:00
                 ...
278790   2021-05-16 23:52:00
278791   2021-05-16 23:52:00
278792   2021-05-16 23:52:00
278793   2021-05-16 23:52:00
278794   2021-05-16 23:59:00
Name: 등록일자, Length: 278795, dtype: datetime64[ns]

In [94]:
df.dtypes

기관 명    object
모델명     object
시리얼     object
서버타입    object
사이트명    object
방문자수    object
날짜      object
등록일자    object
dtype: object