In [32]:
# For Google Colab
from google.colab import drive
drive.mount('/content/Mydrive')
%cd '/content/Mydrive/MyDrive/IOT_hackathon/Github/IOT_hackathon'

Drive already mounted at /content/Mydrive; to attempt to forcibly remount, call drive.mount("/content/Mydrive", force_remount=True).
/content/Mydrive/.shortcut-targets-by-id/1c0Uj2m_Fj74QB5yN9JL2QhAIJ1ijbINP/IOT_hackathon/Github/IOT_hackathon

In [33]:
import pandas as pd

In [34]:
filename2109='/content/Mydrive/MyDrive/IOT_hackathon/Github/IOT_hackathon/data/서울특별시 공공자전거 이용정보(시간대별)_21.09.csv'
filename2110='/content/Mydrive/MyDrive/IOT_hackathon/Github/IOT_hackathon/data/서울특별시 공공자전거 이용정보(시간대별)_21.10.csv'
filename2111='/content/Mydrive/MyDrive/IOT_hackathon/Github/IOT_hackathon/data/서울특별시 공공자전거 이용정보(시간대별)_21.11.csv'
filename2112='/content/Mydrive/MyDrive/IOT_hackathon/Github/IOT_hackathon/data/서울특별시 공공자전거 이용정보(시간대별)_21.12.csv'

In [38]:
data1=pd.read_csv(filename2109,encoding='cp949')
data2=pd.read_csv(filename2110,encoding='cp949')
data3=pd.read_csv(filename2111,encoding='cp949')
data4=pd.read_csv(filename2112,encoding='cp949')

In [39]:
data=pd.concat([data1,data2,data3,data4])

In [40]:
data.head()

,대여일자,대여시간,대여소번호,대여소명,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리,사용시간
0,2021-09-01,0,1337,1337. 돈암성당 옆,정기권,NaN,~10대,1,70.46,0.64,2780.00,14
1,2021-09-01,0,1155,1155. 기쁜우리복지관,정기권,NaN,20대,1,43.86,0.33,1420.00,13
2,2021-09-01,0,1652,1652. 파르코 앞,정기권,NaN,20대,1,0.00,0.00,0.00,6
3,2021-09-01,0,1977,1977. 천왕역 1번 출입구 앞,정기권,NaN,20대,1,56.40,0.41,1758.19,10
4,2021-09-01,0,1662,1662. 노원역7번출구,정기권,NaN,20대,1,\N,\N,0.00,50

In [41]:
#연령대코드 더미변수 생성
data=data.replace('~10대','10대이하')
data=data.replace('70대~','70대이상')
연령대코드_type_dummy=pd.get_dummies(data['연령대코드'],prefix='연령')

In [42]:
#성별 더미변수 생성
data['성별']=data['성별'].fillna('N')
data=data.replace('m','M')
data=data.replace('f','F')
성별_type_dummy=pd.get_dummies(data['성별'],prefix='성별')

In [43]:
#필요없는 칼럼 제거
data=data.drop(['대여구분코드'],axis='columns')
data=data.drop(['성별'],axis='columns')
data=data.drop(['연령대코드'],axis='columns')
data=data.drop(['운동량'],axis='columns')
data=data.drop(['탄소량'],axis='columns')

In [44]:
data=pd.concat([data,성별_type_dummy,연령대코드_type_dummy],axis=1)

In [45]:
data=data.set_index("대여일자")

In [46]:
data.head() #대여일자/시간, 성별, 연령

,대여시간,대여소번호,대여소명,이용건수,이동거리,사용시간,성별_F,성별_M,성별_N,연령_10대이하,연령_20대,연령_30대,연령_40대,연령_50대,연령_60대,연령_70대이상
대여일자,,,,,,,,,,,,,,,,
2021-09-01,0,1337,1337. 돈암성당 옆,1,2780.00,14,0,0,1,1,0,0,0,0,0,0
2021-09-01,0,1155,1155. 기쁜우리복지관,1,1420.00,13,0,0,1,0,1,0,0,0,0,0
2021-09-01,0,1652,1652. 파르코 앞,1,0.00,6,0,0,1,0,1,0,0,0,0,0
2021-09-01,0,1977,1977. 천왕역 1번 출입구 앞,1,1758.19,10,0,0,1,0,1,0,0,0,0,0
2021-09-01,0,1662,1662. 노원역7번출구,1,0.00,50,0,0,1,0,1,0,0,0,0,0

In [ ]:
data.to_csv('./따릉이이용정보.csv')